/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type CredentialDefinitionStruct = {
  id: string;
  issuerId: string;
  schemaId: string;
  credDefType: string;
  tag: string;
  value: string;
};

export type CredentialDefinitionStructOutput = [
  id: string,
  issuerId: string,
  schemaId: string,
  credDefType: string,
  tag: string,
  value: string
] & {
  id: string;
  issuerId: string;
  schemaId: string;
  credDefType: string;
  tag: string;
  value: string;
};

export type CredentialDefinitionMetadataStruct = { created: BigNumberish };

export type CredentialDefinitionMetadataStructOutput = [created: bigint] & {
  created: bigint;
};

export type CredentialDefinitionWithMetadataStruct = {
  credDef: CredentialDefinitionStruct;
  metadata: CredentialDefinitionMetadataStruct;
};

export type CredentialDefinitionWithMetadataStructOutput = [
  credDef: CredentialDefinitionStructOutput,
  metadata: CredentialDefinitionMetadataStructOutput
] & {
  credDef: CredentialDefinitionStructOutput;
  metadata: CredentialDefinitionMetadataStructOutput;
};

export interface CredentialDefinitionRegistryInterfaceInterface
  extends Interface {
  getFunction(
    nameOrSignature:
      | "createCredentialDefinition"
      | "resolveCredentialDefinition"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CredentialDefinitionCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createCredentialDefinition",
    values: [CredentialDefinitionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveCredentialDefinition",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createCredentialDefinition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveCredentialDefinition",
    data: BytesLike
  ): Result;
}

export namespace CredentialDefinitionCreatedEvent {
  export type InputTuple = [
    credentialDefinitionId: string,
    sender: AddressLike
  ];
  export type OutputTuple = [credentialDefinitionId: string, sender: string];
  export interface OutputObject {
    credentialDefinitionId: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialDefinitionRegistryInterface extends BaseContract {
  connect(
    runner?: ContractRunner | null
  ): CredentialDefinitionRegistryInterface;
  waitForDeployment(): Promise<this>;

  interface: CredentialDefinitionRegistryInterfaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createCredentialDefinition: TypedContractMethod<
    [credDef: CredentialDefinitionStruct],
    [void],
    "nonpayable"
  >;

  resolveCredentialDefinition: TypedContractMethod<
    [id: string],
    [CredentialDefinitionWithMetadataStructOutput],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createCredentialDefinition"
  ): TypedContractMethod<
    [credDef: CredentialDefinitionStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveCredentialDefinition"
  ): TypedContractMethod<
    [id: string],
    [CredentialDefinitionWithMetadataStructOutput],
    "nonpayable"
  >;

  getEvent(
    key: "CredentialDefinitionCreated"
  ): TypedContractEvent<
    CredentialDefinitionCreatedEvent.InputTuple,
    CredentialDefinitionCreatedEvent.OutputTuple,
    CredentialDefinitionCreatedEvent.OutputObject
  >;

  filters: {
    "CredentialDefinitionCreated(string,address)": TypedContractEvent<
      CredentialDefinitionCreatedEvent.InputTuple,
      CredentialDefinitionCreatedEvent.OutputTuple,
      CredentialDefinitionCreatedEvent.OutputObject
    >;
    CredentialDefinitionCreated: TypedContractEvent<
      CredentialDefinitionCreatedEvent.InputTuple,
      CredentialDefinitionCreatedEvent.OutputTuple,
      CredentialDefinitionCreatedEvent.OutputObject
    >;
  };
}
