/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CredentialDefinitionRegistry } from "./CredentialDefinitionRegistry";
export type { CredentialDefinitionRegistryInterface } from "./CredentialDefinitionRegistryInterface";
export type { RevocationRegistry } from "./RevocationRegistry";
export type { RevocationRegistryInterface } from "./RevocationRegistryInterface";
export type { SchemaRegistry } from "./SchemaRegistry";
export type { SchemaRegistryInterface } from "./SchemaRegistryInterface";
