/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type RevocationStruct = {
  id: string;
  issuerId: string;
  credDefId: string;
};

export type RevocationStructOutput = [
  id: string,
  issuerId: string,
  credDefId: string
] & { id: string; issuerId: string; credDefId: string };

export type RevocationRegStruct = {
  ver: string;
  id: string;
  revocDefType: string;
  credDefId: string;
  tag: string;
  value: string;
  issuerId: string;
};

export type RevocationRegStructOutput = [
  ver: string,
  id: string,
  revocDefType: string,
  credDefId: string,
  tag: string,
  value: string,
  issuerId: string
] & {
  ver: string;
  id: string;
  revocDefType: string;
  credDefId: string;
  tag: string;
  value: string;
  issuerId: string;
};

export type RevocationRegMetadataStruct = {
  created: BigNumberish;
  creator: AddressLike;
  updated: BigNumberish;
};

export type RevocationRegMetadataStructOutput = [
  created: bigint,
  creator: string,
  updated: bigint
] & { created: bigint; creator: string; updated: bigint };

export type RevocationRegWithMetadataStruct = {
  revocationReg: RevocationRegStruct;
  metadata: RevocationRegMetadataStruct;
};

export type RevocationRegWithMetadataStructOutput = [
  revocationReg: RevocationRegStructOutput,
  metadata: RevocationRegMetadataStructOutput
] & {
  revocationReg: RevocationRegStructOutput;
  metadata: RevocationRegMetadataStructOutput;
};

export interface RevocationRegistryInterfaceInterface extends Interface {
  getFunction(
    nameOrSignature: "createRevocation" | "resolveRevocation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialRevoked"
      | "CredentialUnrevoked"
      | "RevListCreated"
      | "RevocationCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createRevocation",
    values: [RevocationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveRevocation",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createRevocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveRevocation",
    data: BytesLike
  ): Result;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [RevocationId: string, sender: AddressLike];
  export type OutputTuple = [RevocationId: string, sender: string];
  export interface OutputObject {
    RevocationId: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialUnrevokedEvent {
  export type InputTuple = [RevocationId: string, sender: AddressLike];
  export type OutputTuple = [RevocationId: string, sender: string];
  export interface OutputObject {
    RevocationId: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevListCreatedEvent {
  export type InputTuple = [RevRegId: string, sender: AddressLike];
  export type OutputTuple = [RevRegId: string, sender: string];
  export interface OutputObject {
    RevRegId: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevocationCreatedEvent {
  export type InputTuple = [RevocationId: string, sender: AddressLike];
  export type OutputTuple = [RevocationId: string, sender: string];
  export interface OutputObject {
    RevocationId: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RevocationRegistryInterface extends BaseContract {
  connect(runner?: ContractRunner | null): RevocationRegistryInterface;
  waitForDeployment(): Promise<this>;

  interface: RevocationRegistryInterfaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createRevocation: TypedContractMethod<
    [credDef: RevocationStruct],
    [void],
    "nonpayable"
  >;

  resolveRevocation: TypedContractMethod<
    [id: string],
    [RevocationRegWithMetadataStructOutput],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createRevocation"
  ): TypedContractMethod<[credDef: RevocationStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveRevocation"
  ): TypedContractMethod<
    [id: string],
    [RevocationRegWithMetadataStructOutput],
    "nonpayable"
  >;

  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialUnrevoked"
  ): TypedContractEvent<
    CredentialUnrevokedEvent.InputTuple,
    CredentialUnrevokedEvent.OutputTuple,
    CredentialUnrevokedEvent.OutputObject
  >;
  getEvent(
    key: "RevListCreated"
  ): TypedContractEvent<
    RevListCreatedEvent.InputTuple,
    RevListCreatedEvent.OutputTuple,
    RevListCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RevocationCreated"
  ): TypedContractEvent<
    RevocationCreatedEvent.InputTuple,
    RevocationCreatedEvent.OutputTuple,
    RevocationCreatedEvent.OutputObject
  >;

  filters: {
    "CredentialRevoked(string,address)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "CredentialUnrevoked(string,address)": TypedContractEvent<
      CredentialUnrevokedEvent.InputTuple,
      CredentialUnrevokedEvent.OutputTuple,
      CredentialUnrevokedEvent.OutputObject
    >;
    CredentialUnrevoked: TypedContractEvent<
      CredentialUnrevokedEvent.InputTuple,
      CredentialUnrevokedEvent.OutputTuple,
      CredentialUnrevokedEvent.OutputObject
    >;

    "RevListCreated(string,address)": TypedContractEvent<
      RevListCreatedEvent.InputTuple,
      RevListCreatedEvent.OutputTuple,
      RevListCreatedEvent.OutputObject
    >;
    RevListCreated: TypedContractEvent<
      RevListCreatedEvent.InputTuple,
      RevListCreatedEvent.OutputTuple,
      RevListCreatedEvent.OutputObject
    >;

    "RevocationCreated(string,address)": TypedContractEvent<
      RevocationCreatedEvent.InputTuple,
      RevocationCreatedEvent.OutputTuple,
      RevocationCreatedEvent.OutputObject
    >;
    RevocationCreated: TypedContractEvent<
      RevocationCreatedEvent.InputTuple,
      RevocationCreatedEvent.OutputTuple,
      RevocationCreatedEvent.OutputObject
    >;
  };
}
