/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type SchemaStruct = {
  id: string;
  issuerId: string;
  name: string;
  version: string;
  attrNames: string[];
};

export type SchemaStructOutput = [
  id: string,
  issuerId: string,
  name: string,
  version: string,
  attrNames: string[]
] & {
  id: string;
  issuerId: string;
  name: string;
  version: string;
  attrNames: string[];
};

export type SchemaMetadataStruct = { created: BigNumberish };

export type SchemaMetadataStructOutput = [created: bigint] & {
  created: bigint;
};

export type SchemaWithMetadataStruct = {
  schema: SchemaStruct;
  metadata: SchemaMetadataStruct;
};

export type SchemaWithMetadataStructOutput = [
  schema: SchemaStructOutput,
  metadata: SchemaMetadataStructOutput
] & { schema: SchemaStructOutput; metadata: SchemaMetadataStructOutput };

export interface SchemaRegistryInterfaceInterface extends Interface {
  getFunction(
    nameOrSignature: "createSchema" | "resolveSchema"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SchemaCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createSchema",
    values: [SchemaStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveSchema",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSchema",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveSchema",
    data: BytesLike
  ): Result;
}

export namespace SchemaCreatedEvent {
  export type InputTuple = [schemaId: string, sender: AddressLike];
  export type OutputTuple = [schemaId: string, sender: string];
  export interface OutputObject {
    schemaId: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SchemaRegistryInterface extends BaseContract {
  connect(runner?: ContractRunner | null): SchemaRegistryInterface;
  waitForDeployment(): Promise<this>;

  interface: SchemaRegistryInterfaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createSchema: TypedContractMethod<
    [schema: SchemaStruct],
    [void],
    "nonpayable"
  >;

  resolveSchema: TypedContractMethod<
    [id: string],
    [SchemaWithMetadataStructOutput],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSchema"
  ): TypedContractMethod<[schema: SchemaStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveSchema"
  ): TypedContractMethod<
    [id: string],
    [SchemaWithMetadataStructOutput],
    "nonpayable"
  >;

  getEvent(
    key: "SchemaCreated"
  ): TypedContractEvent<
    SchemaCreatedEvent.InputTuple,
    SchemaCreatedEvent.OutputTuple,
    SchemaCreatedEvent.OutputObject
  >;

  filters: {
    "SchemaCreated(string,address)": TypedContractEvent<
      SchemaCreatedEvent.InputTuple,
      SchemaCreatedEvent.OutputTuple,
      SchemaCreatedEvent.OutputObject
    >;
    SchemaCreated: TypedContractEvent<
      SchemaCreatedEvent.InputTuple,
      SchemaCreatedEvent.OutputTuple,
      SchemaCreatedEvent.OutputObject
    >;
  };
}
