/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ValidatorControl } from "./ValidatorControl";
export type { ValidatorSmartContractInterface } from "./ValidatorSmartContractInterface";
