/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccountControl } from "./AccountControl";
export type { AccountControlInterface } from "./AccountControlInterface";
export type { RoleControl } from "./RoleControl";
export type { RoleControlInterface } from "./RoleControlInterface";
