/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RoleControlInterfaceInterface extends Interface {
  getFunction(
    nameOrSignature: "assignRole" | "getRoleCount" | "hasRole" | "revokeRole"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RoleAssigned" | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assignRole",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "assignRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
}

export namespace RoleAssignedEvent {
  export type InputTuple = [
    role: BigNumberish,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: bigint, account: string, sender: string];
  export interface OutputObject {
    role: bigint;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BigNumberish,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: bigint, account: string, sender: string];
  export interface OutputObject {
    role: bigint;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RoleControlInterface extends BaseContract {
  connect(runner?: ContractRunner | null): RoleControlInterface;
  waitForDeployment(): Promise<this>;

  interface: RoleControlInterfaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assignRole: TypedContractMethod<
    [role: BigNumberish, account: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getRoleCount: TypedContractMethod<[role: BigNumberish], [bigint], "view">;

  hasRole: TypedContractMethod<
    [role: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;

  revokeRole: TypedContractMethod<
    [role: BigNumberish, account: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assignRole"
  ): TypedContractMethod<
    [role: BigNumberish, account: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleCount"
  ): TypedContractMethod<[role: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BigNumberish, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BigNumberish, account: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "RoleAssigned"
  ): TypedContractEvent<
    RoleAssignedEvent.InputTuple,
    RoleAssignedEvent.OutputTuple,
    RoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "RoleAssigned(uint8,address,address)": TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;
    RoleAssigned: TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;

    "RoleRevoked(uint8,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
