/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { NotUpgradable__factory } from "./NotUpgradable__factory";
export { SimpleContract__factory } from "./SimpleContract__factory";
export { UpgradablePrototypeV1__factory } from "./UpgradablePrototypeV1__factory";
export { UpgradablePrototypeV2__factory } from "./UpgradablePrototypeV2__factory";
