/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AccountControlInterface,
  AccountControlInterfaceInterface,
} from "../../../contracts/auth/AccountControlInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gasPrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gasLimit",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
    ],
    name: "transactionAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "result",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AccountControlInterface__factory {
  static readonly abi = _abi;
  static createInterface(): AccountControlInterfaceInterface {
    return new Interface(_abi) as AccountControlInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AccountControlInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AccountControlInterface;
  }
}
