/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  RoleControlInterface,
  RoleControlInterfaceInterface,
} from "../../../contracts/auth/RoleControlInterface";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "enum RoleControlInterface.ROLES",
        name: "role",
        type: "uint8",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleAssigned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "enum RoleControlInterface.ROLES",
        name: "role",
        type: "uint8",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "enum RoleControlInterface.ROLES",
        name: "role",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "assignRole",
    outputs: [
      {
        internalType: "enum RoleControlInterface.ROLES",
        name: "assignedRole",
        type: "uint8",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum RoleControlInterface.ROLES",
        name: "role",
        type: "uint8",
      },
    ],
    name: "getRoleCount",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum RoleControlInterface.ROLES",
        name: "role",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum RoleControlInterface.ROLES",
        name: "role",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "revokeRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class RoleControlInterface__factory {
  static readonly abi = _abi;
  static createInterface(): RoleControlInterfaceInterface {
    return new Interface(_abi) as RoleControlInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RoleControlInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as RoleControlInterface;
  }
}
