/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CredentialDefinitionRegistry__factory } from "./CredentialDefinitionRegistry__factory";
export { CredentialDefinitionRegistryInterface__factory } from "./CredentialDefinitionRegistryInterface__factory";
export { RevocationRegistry__factory } from "./RevocationRegistry__factory";
export { RevocationRegistryInterface__factory } from "./RevocationRegistryInterface__factory";
export { SchemaRegistry__factory } from "./SchemaRegistry__factory";
export { SchemaRegistryInterface__factory } from "./SchemaRegistryInterface__factory";
