/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SchemaRegistryInterface,
  SchemaRegistryInterfaceInterface,
} from "../../../contracts/cl/SchemaRegistryInterface";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "schemaId",
        type: "string",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "SchemaCreated",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "id",
            type: "string",
          },
          {
            internalType: "string",
            name: "issuerId",
            type: "string",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "version",
            type: "string",
          },
          {
            internalType: "string[]",
            name: "attrNames",
            type: "string[]",
          },
        ],
        internalType: "struct Schema",
        name: "schema",
        type: "tuple",
      },
    ],
    name: "createSchema",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "id",
        type: "string",
      },
    ],
    name: "resolveSchema",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "string",
                name: "id",
                type: "string",
              },
              {
                internalType: "string",
                name: "issuerId",
                type: "string",
              },
              {
                internalType: "string",
                name: "name",
                type: "string",
              },
              {
                internalType: "string",
                name: "version",
                type: "string",
              },
              {
                internalType: "string[]",
                name: "attrNames",
                type: "string[]",
              },
            ],
            internalType: "struct Schema",
            name: "schema",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "created",
                type: "uint256",
              },
            ],
            internalType: "struct SchemaMetadata",
            name: "metadata",
            type: "tuple",
          },
        ],
        internalType: "struct SchemaWithMetadata",
        name: "schemaWithMetadata",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class SchemaRegistryInterface__factory {
  static readonly abi = _abi;
  static createInterface(): SchemaRegistryInterfaceInterface {
    return new Interface(_abi) as SchemaRegistryInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SchemaRegistryInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as SchemaRegistryInterface;
  }
}
