/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EthereumExtDidRegistry__factory } from "./EthereumExtDidRegistry__factory";
export { IndyDidRegistry__factory } from "./IndyDidRegistry__factory";
export { IndyDidRegistryInterface__factory } from "./IndyDidRegistryInterface__factory";
export { IndyDidValidator__factory } from "./IndyDidValidator__factory";
export { UniversalDidResolver__factory } from "./UniversalDidResolver__factory";
export { UniversalDidResolverInterface__factory } from "./UniversalDidResolverInterface__factory";
