/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ControlledUpgradeable } from "./ControlledUpgradeable";
export type { UpgradeControl } from "./UpgradeControl";
export type { UpgradeControlInterface } from "./UpgradeControlInterface";
