/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NotUpgradable } from "./NotUpgradable";
export type { SimpleContract } from "./SimpleContract";
export type { UpgradablePrototypeV1 } from "./UpgradablePrototypeV1";
export type { UpgradablePrototypeV2 } from "./UpgradablePrototypeV2";
