/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EthereumExtDidRegistry } from "./EthereumExtDidRegistry";
export type { IndyDidRegistry } from "./IndyDidRegistry";
export type { IndyDidRegistryInterface } from "./IndyDidRegistryInterface";
export type { IndyDidValidator } from "./IndyDidValidator";
export type { UniversalDidResolver } from "./UniversalDidResolver";
export type { UniversalDidResolverInterface } from "./UniversalDidResolverInterface";
