/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type VerificationMethodStruct = {
  id: string;
  verificationMethodType: string;
  controller: string;
  publicKeyJwk: string;
  publicKeyMultibase: string;
};

export type VerificationMethodStructOutput = [
  id: string,
  verificationMethodType: string,
  controller: string,
  publicKeyJwk: string,
  publicKeyMultibase: string
] & {
  id: string;
  verificationMethodType: string;
  controller: string;
  publicKeyJwk: string;
  publicKeyMultibase: string;
};

export type VerificationRelationshipStruct = {
  id: string;
  verificationMethod: VerificationMethodStruct;
};

export type VerificationRelationshipStructOutput = [
  id: string,
  verificationMethod: VerificationMethodStructOutput
] & { id: string; verificationMethod: VerificationMethodStructOutput };

export type ServiceStruct = {
  id: string;
  serviceType: string;
  serviceEndpoint: string;
  accept: string[];
  routingKeys: string[];
};

export type ServiceStructOutput = [
  id: string,
  serviceType: string,
  serviceEndpoint: string,
  accept: string[],
  routingKeys: string[]
] & {
  id: string;
  serviceType: string;
  serviceEndpoint: string;
  accept: string[];
  routingKeys: string[];
};

export type DidDocumentStruct = {
  context: string[];
  id: string;
  controller: string[];
  verificationMethod: VerificationMethodStruct[];
  authentication: VerificationRelationshipStruct[];
  assertionMethod: VerificationRelationshipStruct[];
  capabilityInvocation: VerificationRelationshipStruct[];
  capabilityDelegation: VerificationRelationshipStruct[];
  keyAgreement: VerificationRelationshipStruct[];
  service: ServiceStruct[];
  alsoKnownAs: string[];
};

export type DidDocumentStructOutput = [
  context: string[],
  id: string,
  controller: string[],
  verificationMethod: VerificationMethodStructOutput[],
  authentication: VerificationRelationshipStructOutput[],
  assertionMethod: VerificationRelationshipStructOutput[],
  capabilityInvocation: VerificationRelationshipStructOutput[],
  capabilityDelegation: VerificationRelationshipStructOutput[],
  keyAgreement: VerificationRelationshipStructOutput[],
  service: ServiceStructOutput[],
  alsoKnownAs: string[]
] & {
  context: string[];
  id: string;
  controller: string[];
  verificationMethod: VerificationMethodStructOutput[];
  authentication: VerificationRelationshipStructOutput[];
  assertionMethod: VerificationRelationshipStructOutput[];
  capabilityInvocation: VerificationRelationshipStructOutput[];
  capabilityDelegation: VerificationRelationshipStructOutput[];
  keyAgreement: VerificationRelationshipStructOutput[];
  service: ServiceStructOutput[];
  alsoKnownAs: string[];
};

export type DidMetadataStruct = {
  creator: AddressLike;
  created: BigNumberish;
  updated: BigNumberish;
  deactivated: boolean;
};

export type DidMetadataStructOutput = [
  creator: string,
  created: bigint,
  updated: bigint,
  deactivated: boolean
] & { creator: string; created: bigint; updated: bigint; deactivated: boolean };

export type DidDocumentStorageStruct = {
  document: DidDocumentStruct;
  metadata: DidMetadataStruct;
};

export type DidDocumentStorageStructOutput = [
  document: DidDocumentStructOutput,
  metadata: DidMetadataStructOutput
] & { document: DidDocumentStructOutput; metadata: DidMetadataStructOutput };

export interface IndyDidRegistryInterfaceInterface extends Interface {
  getFunction(
    nameOrSignature: "createDid" | "deactivateDid" | "resolveDid" | "updateDid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DIDCreated" | "DIDDeactivated" | "DIDUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createDid",
    values: [DidDocumentStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateDid",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "resolveDid", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateDid",
    values: [DidDocumentStruct]
  ): string;

  decodeFunctionResult(functionFragment: "createDid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateDid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolveDid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateDid", data: BytesLike): Result;
}

export namespace DIDCreatedEvent {
  export type InputTuple = [did: string];
  export type OutputTuple = [did: string];
  export interface OutputObject {
    did: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDDeactivatedEvent {
  export type InputTuple = [did: string];
  export type OutputTuple = [did: string];
  export interface OutputObject {
    did: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDUpdatedEvent {
  export type InputTuple = [did: string];
  export type OutputTuple = [did: string];
  export interface OutputObject {
    did: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IndyDidRegistryInterface extends BaseContract {
  connect(runner?: ContractRunner | null): IndyDidRegistryInterface;
  waitForDeployment(): Promise<this>;

  interface: IndyDidRegistryInterfaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createDid: TypedContractMethod<
    [document: DidDocumentStruct],
    [void],
    "nonpayable"
  >;

  deactivateDid: TypedContractMethod<[id: string], [void], "nonpayable">;

  resolveDid: TypedContractMethod<
    [id: string],
    [DidDocumentStorageStructOutput],
    "view"
  >;

  updateDid: TypedContractMethod<
    [document: DidDocumentStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createDid"
  ): TypedContractMethod<[document: DidDocumentStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateDid"
  ): TypedContractMethod<[id: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDid"
  ): TypedContractMethod<
    [id: string],
    [DidDocumentStorageStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateDid"
  ): TypedContractMethod<[document: DidDocumentStruct], [void], "nonpayable">;

  getEvent(
    key: "DIDCreated"
  ): TypedContractEvent<
    DIDCreatedEvent.InputTuple,
    DIDCreatedEvent.OutputTuple,
    DIDCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DIDDeactivated"
  ): TypedContractEvent<
    DIDDeactivatedEvent.InputTuple,
    DIDDeactivatedEvent.OutputTuple,
    DIDDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "DIDUpdated"
  ): TypedContractEvent<
    DIDUpdatedEvent.InputTuple,
    DIDUpdatedEvent.OutputTuple,
    DIDUpdatedEvent.OutputObject
  >;

  filters: {
    "DIDCreated(string)": TypedContractEvent<
      DIDCreatedEvent.InputTuple,
      DIDCreatedEvent.OutputTuple,
      DIDCreatedEvent.OutputObject
    >;
    DIDCreated: TypedContractEvent<
      DIDCreatedEvent.InputTuple,
      DIDCreatedEvent.OutputTuple,
      DIDCreatedEvent.OutputObject
    >;

    "DIDDeactivated(string)": TypedContractEvent<
      DIDDeactivatedEvent.InputTuple,
      DIDDeactivatedEvent.OutputTuple,
      DIDDeactivatedEvent.OutputObject
    >;
    DIDDeactivated: TypedContractEvent<
      DIDDeactivatedEvent.InputTuple,
      DIDDeactivatedEvent.OutputTuple,
      DIDDeactivatedEvent.OutputObject
    >;

    "DIDUpdated(string)": TypedContractEvent<
      DIDUpdatedEvent.InputTuple,
      DIDUpdatedEvent.OutputTuple,
      DIDUpdatedEvent.OutputObject
    >;
    DIDUpdated: TypedContractEvent<
      DIDUpdatedEvent.InputTuple,
      DIDUpdatedEvent.OutputTuple,
      DIDUpdatedEvent.OutputObject
    >;
  };
}
