/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type VerificationMethodStruct = {
  id: string;
  verificationMethodType: string;
  controller: string;
  publicKeyJwk: string;
  publicKeyMultibase: string;
};

export type VerificationMethodStructOutput = [
  id: string,
  verificationMethodType: string,
  controller: string,
  publicKeyJwk: string,
  publicKeyMultibase: string
] & {
  id: string;
  verificationMethodType: string;
  controller: string;
  publicKeyJwk: string;
  publicKeyMultibase: string;
};

export type VerificationRelationshipStruct = {
  id: string;
  verificationMethod: VerificationMethodStruct;
};

export type VerificationRelationshipStructOutput = [
  id: string,
  verificationMethod: VerificationMethodStructOutput
] & { id: string; verificationMethod: VerificationMethodStructOutput };

export type ServiceStruct = {
  id: string;
  serviceType: string;
  serviceEndpoint: string;
  accept: string[];
  routingKeys: string[];
};

export type ServiceStructOutput = [
  id: string,
  serviceType: string,
  serviceEndpoint: string,
  accept: string[],
  routingKeys: string[]
] & {
  id: string;
  serviceType: string;
  serviceEndpoint: string;
  accept: string[];
  routingKeys: string[];
};

export type DidDocumentStruct = {
  context: string[];
  id: string;
  controller: string[];
  verificationMethod: VerificationMethodStruct[];
  authentication: VerificationRelationshipStruct[];
  assertionMethod: VerificationRelationshipStruct[];
  capabilityInvocation: VerificationRelationshipStruct[];
  capabilityDelegation: VerificationRelationshipStruct[];
  keyAgreement: VerificationRelationshipStruct[];
  service: ServiceStruct[];
  alsoKnownAs: string[];
};

export type DidDocumentStructOutput = [
  context: string[],
  id: string,
  controller: string[],
  verificationMethod: VerificationMethodStructOutput[],
  authentication: VerificationRelationshipStructOutput[],
  assertionMethod: VerificationRelationshipStructOutput[],
  capabilityInvocation: VerificationRelationshipStructOutput[],
  capabilityDelegation: VerificationRelationshipStructOutput[],
  keyAgreement: VerificationRelationshipStructOutput[],
  service: ServiceStructOutput[],
  alsoKnownAs: string[]
] & {
  context: string[];
  id: string;
  controller: string[];
  verificationMethod: VerificationMethodStructOutput[];
  authentication: VerificationRelationshipStructOutput[];
  assertionMethod: VerificationRelationshipStructOutput[];
  capabilityInvocation: VerificationRelationshipStructOutput[];
  capabilityDelegation: VerificationRelationshipStructOutput[];
  keyAgreement: VerificationRelationshipStructOutput[];
  service: ServiceStructOutput[];
  alsoKnownAs: string[];
};

export type DidMetadataStruct = {
  creator: AddressLike;
  created: BigNumberish;
  updated: BigNumberish;
  deactivated: boolean;
};

export type DidMetadataStructOutput = [
  creator: string,
  created: bigint,
  updated: bigint,
  deactivated: boolean
] & { creator: string; created: bigint; updated: bigint; deactivated: boolean };

export interface UniversalDidResolverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "initialize"
      | "proxiableUUID"
      | "resolveDocument"
      | "resolveMetadata"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Initialized" | "Upgraded"): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDocument",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMetadata",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UniversalDidResolver extends BaseContract {
  connect(runner?: ContractRunner | null): UniversalDidResolver;
  waitForDeployment(): Promise<this>;

  interface: UniversalDidResolverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [
      upgradeControlAddress: AddressLike,
      didRegistryddress: AddressLike,
      ethereumDIDRegistryAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  resolveDocument: TypedContractMethod<
    [id: string],
    [DidDocumentStructOutput],
    "view"
  >;

  resolveMetadata: TypedContractMethod<
    [id: string],
    [DidMetadataStructOutput],
    "view"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      upgradeControlAddress: AddressLike,
      didRegistryddress: AddressLike,
      ethereumDIDRegistryAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveDocument"
  ): TypedContractMethod<[id: string], [DidDocumentStructOutput], "view">;
  getFunction(
    nameOrSignature: "resolveMetadata"
  ): TypedContractMethod<[id: string], [DidMetadataStructOutput], "view">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
