/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type VerificationMethodStruct = {
  id: string;
  verificationMethodType: string;
  controller: string;
  publicKeyJwk: string;
  publicKeyMultibase: string;
};

export type VerificationMethodStructOutput = [
  id: string,
  verificationMethodType: string,
  controller: string,
  publicKeyJwk: string,
  publicKeyMultibase: string
] & {
  id: string;
  verificationMethodType: string;
  controller: string;
  publicKeyJwk: string;
  publicKeyMultibase: string;
};

export type VerificationRelationshipStruct = {
  id: string;
  verificationMethod: VerificationMethodStruct;
};

export type VerificationRelationshipStructOutput = [
  id: string,
  verificationMethod: VerificationMethodStructOutput
] & { id: string; verificationMethod: VerificationMethodStructOutput };

export type ServiceStruct = {
  id: string;
  serviceType: string;
  serviceEndpoint: string;
  accept: string[];
  routingKeys: string[];
};

export type ServiceStructOutput = [
  id: string,
  serviceType: string,
  serviceEndpoint: string,
  accept: string[],
  routingKeys: string[]
] & {
  id: string;
  serviceType: string;
  serviceEndpoint: string;
  accept: string[];
  routingKeys: string[];
};

export type DidDocumentStruct = {
  context: string[];
  id: string;
  controller: string[];
  verificationMethod: VerificationMethodStruct[];
  authentication: VerificationRelationshipStruct[];
  assertionMethod: VerificationRelationshipStruct[];
  capabilityInvocation: VerificationRelationshipStruct[];
  capabilityDelegation: VerificationRelationshipStruct[];
  keyAgreement: VerificationRelationshipStruct[];
  service: ServiceStruct[];
  alsoKnownAs: string[];
};

export type DidDocumentStructOutput = [
  context: string[],
  id: string,
  controller: string[],
  verificationMethod: VerificationMethodStructOutput[],
  authentication: VerificationRelationshipStructOutput[],
  assertionMethod: VerificationRelationshipStructOutput[],
  capabilityInvocation: VerificationRelationshipStructOutput[],
  capabilityDelegation: VerificationRelationshipStructOutput[],
  keyAgreement: VerificationRelationshipStructOutput[],
  service: ServiceStructOutput[],
  alsoKnownAs: string[]
] & {
  context: string[];
  id: string;
  controller: string[];
  verificationMethod: VerificationMethodStructOutput[];
  authentication: VerificationRelationshipStructOutput[];
  assertionMethod: VerificationRelationshipStructOutput[];
  capabilityInvocation: VerificationRelationshipStructOutput[];
  capabilityDelegation: VerificationRelationshipStructOutput[];
  keyAgreement: VerificationRelationshipStructOutput[];
  service: ServiceStructOutput[];
  alsoKnownAs: string[];
};

export type DidMetadataStruct = {
  creator: AddressLike;
  created: BigNumberish;
  updated: BigNumberish;
  deactivated: boolean;
};

export type DidMetadataStructOutput = [
  creator: string,
  created: bigint,
  updated: bigint,
  deactivated: boolean
] & { creator: string; created: bigint; updated: bigint; deactivated: boolean };

export interface UniversalDidResolverInterfaceInterface extends Interface {
  getFunction(
    nameOrSignature: "resolveDocument" | "resolveMetadata"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "resolveDocument",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMetadata",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "resolveDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMetadata",
    data: BytesLike
  ): Result;
}

export interface UniversalDidResolverInterface extends BaseContract {
  connect(runner?: ContractRunner | null): UniversalDidResolverInterface;
  waitForDeployment(): Promise<this>;

  interface: UniversalDidResolverInterfaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  resolveDocument: TypedContractMethod<
    [id: string],
    [DidDocumentStructOutput],
    "view"
  >;

  resolveMetadata: TypedContractMethod<
    [id: string],
    [DidMetadataStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "resolveDocument"
  ): TypedContractMethod<[id: string], [DidDocumentStructOutput], "view">;
  getFunction(
    nameOrSignature: "resolveMetadata"
  ): TypedContractMethod<[id: string], [DidMetadataStructOutput], "view">;

  filters: {};
}
